"use client";

import { useEffect, useMemo, useState } from "react";

const starterFiles = {
  "app/page.html": "<!doctype html>\n<html lang=\"vi\">\n<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>New Project</title></head>\n<body><main><h1>New Project</h1><p>Bắt đầu bằng yêu cầu ở Agent.</p></main></body>\n</html>",
  "app/styles.css": "body{font-family:system-ui;margin:0;padding:40px;background:#0b0d12;color:#fff}main{max-width:900px;margin:auto}",
  "app/app.js": "console.log(\"AI Software Factory workspace ready\");",
  "README.md": "# Project\n\nWorkspace generated by AI Software Factory."
};

export default function EngineeringWorkspace({ prompt, setPrompt, onBuild, busy, previewHtml, setPreviewHtml, logs, setLogs }) {
  const [files, setFiles] = useState(()=>{try{return JSON.parse(localStorage.getItem("asf.ide.files")||"null")||starterFiles}catch{return starterFiles}});
  const [activeFile, setActiveFile] = useState("app/page.html");
  const [tab, setTab] = useState("code");
  const [terminal, setTerminal] = useState(["$ workspace init","✓ Local project workspace ready","✓ Live Preview sandbox available"]);
  const [history, setHistory] = useState([]);
  const [agentBusy, setAgentBusy] = useState(false);
  const [status, setStatus] = useState("Ready");

  const code = files[activeFile] || "";
  const fileList = Object.keys(files);
  const changed = useMemo(() => history.length, [history]);
  useEffect(()=>{try{localStorage.setItem("asf.ide.files",JSON.stringify(files))}catch{}},[files]);

  function updateCode(value){
    setHistory(h=>[...h,{file:activeFile,before:files[activeFile]||"",after:value,time:new Date().toISOString()}]);
    setFiles(f=>({...f,[activeFile]:value}));
    setStatus("Modified");
  }

  function resetFile(){
    if(!confirm("Khôi phục file này về bản starter?")) return;
    setFiles(f=>({...f,[activeFile]:starterFiles[activeFile]||""}));
    setStatus("Restored");
  }

  async function agentBuild(){
    if(!prompt.trim() || agentBusy) return;
    setAgentBusy(true); setStatus("Agent planning…");
    setTerminal(t=>[...t, "$ agent build", "→ phân tích yêu cầu…"]);
    try{
      const r=await fetch("/api/ai",{method:"POST",headers:{"content-type":"application/json"},
        body:JSON.stringify({action:"build",prompt:prompt.trim(),providers:window.__ASF_PROVIDERS__||[],selected:"auto"})});
      const d=await r.json();
      if(!r.ok) throw new Error(d.error||"Agent build failed");
      const html=d.html||"";
      setFiles(f=>({...f,"app/page.html":html}));
      setPreviewHtml(html);
      setHistory(h=>[...h,{file:"app/page.html",before:files["app/page.html"]||"",after:html,time:new Date().toISOString()}]);
      setTerminal(t=>[...t,"✓ AI generated app/page.html","✓ Preview updated","✓ Provider: "+(d.provider||"free-router")]);
      setLogs(l=>[...l,"Agent: build OK → "+(d.provider||"router")]);
      setStatus("Built");
    }catch(e){
      setTerminal(t=>[...t,"✕ "+e.message]);
      setLogs(l=>[...l,"Agent: "+e.message]);
      setStatus("Error");
    }finally{setAgentBusy(false)}
  }

  function runPreview(){
    const html=files["app/page.html"]||"";
    setPreviewHtml(html); setStatus("Preview running");
    setTerminal(t=>[...t,"$ run preview","✓ iframe preview started"]);
  }

  function command(){
    setTerminal(t=>[...t,"$ status","workspace: browser-local","files: "+fileList.length,"changes: "+changed,"preview: "+(previewHtml?"ready":"not built"),"note: no server shell is executed from this browser workspace"]);
  }

  return <section className="ide">
    <div className="ide-top">
      <div><div className="eyebrow">Engineering workspace</div><h1>AI Code Studio</h1><p>Agent + Code + Diff + Preview trong một workspace.</p></div>
      <div className="row">
        <span className={"ide-status "+(status==="Error"?"bad":status==="Built"||status==="Preview running"?"good":"")}>{status}</span>
        <button className="btn" onClick={command}>Workspace status</button>
        <button className="btn primary" disabled={agentBusy||busy} onClick={agentBuild}>{agentBusy?"Agent đang làm…":"✦ Agent Build"}</button>
      </div>
    </div>

    <div className="ide-grid">
      <aside className="ide-files card">
        <div className="ide-head"><b>EXPLORER</b><span>{fileList.length} files</span></div>
        {fileList.map(f=><button key={f} className={"file-item "+(f===activeFile?"active":"")} onClick={()=>{setActiveFile(f);setTab("code")}}>
          <span>{f.endsWith(".html")?"◉":f.endsWith(".css")?"◌":f.endsWith(".js")?"◇":"▱"}</span>{f}
        </button>)}
        <div className="ide-section"><b>SOURCE CONTROL</b><span>{changed} changes</span></div>
        <div className="change-list">{history.slice(-8).reverse().map((x,i)=><div key={i}><b>M</b> {x.file}</div>)}</div>
      </aside>

      <section className="ide-center">
        <div className="ide-tabs">
          <button className={tab==="code"?"on":""} onClick={()=>setTab("code")}>CODE</button>
          <button className={tab==="diff"?"on":""} onClick={()=>setTab("diff")}>DIFF {changed?"("+changed+")":""}</button>
          <button className={tab==="agent"?"on":""} onClick={()=>setTab("agent")}>AGENT</button>
        </div>

        {tab==="code" && <div className="editor-wrap">
          <div className="editor-head"><span>{activeFile}</span><div className="row"><button onClick={resetFile}>Reset</button><button onClick={runPreview}>Run ▶</button></div></div>
          <textarea className="code-editor" value={code} onChange={e=>updateCode(e.target.value)} spellCheck={false}/>
        </div>}

        {tab==="diff" && <div className="diff-view">
          <div className="editor-head"><span>Latest changes</span><span>{changed} edits</span></div>
          {!history.length?<div className="ide-empty">Chưa có thay đổi.</div>:history.slice(-5).reverse().map((x,i)=><div className="diff-block" key={i}><b>{x.file}</b><pre><span className="minus">- {x.before.slice(0,500)}</span>{"\n"}<span className="plus">+ {x.after.slice(0,500)}</span></pre></div>)}
        </div>}

        {tab==="agent" && <div className="agent-panel">
          <h2>Agent Task</h2>
          <p className="muted">Mô tả việc cần làm. Agent sẽ tạo/đổi preview trong workspace hiện tại.</p>
          <textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ví dụ: Xây dashboard quản lý đơn hàng..."/>
          <button className="btn primary" disabled={agentBusy} onClick={agentBuild}>{agentBusy?"Đang thực thi…":"Build & Verify"}</button>
          <div className="agent-steps"><div>✓ Understand request</div><div>✓ Generate implementation</div><div>✓ Update files</div><div>✓ Live preview</div></div>
        </div>}

        <div className="terminal">
          <div className="terminal-head"><b>TERMINAL</b><span>Browser workspace</span></div>
          <div className="terminal-body">{terminal.slice(-14).map((x,i)=><div key={i}>{x}</div>)}</div>
        </div>
      </section>

      <aside className="ide-preview card">
        <div className="ide-head"><b>PREVIEW</b><span>{previewHtml?"LIVE":"EMPTY"}</span></div>
        {previewHtml?<iframe title="AI Code Studio Preview" srcDoc={previewHtml} sandbox="allow-scripts allow-forms"/>:<div className="ide-empty">Chưa có preview.<br/>Dùng Agent Build hoặc Run.</div>}
      </aside>
    </div>
  </section>
}
